# ???????
db.url=jdbc:opengauss://192.168.56.101:26000/survey_db
db.user=Xiaohao
db.password=xh.2023?!666
db.driver=org.opengauss.Driver

# ????????
db.pool.initialSize=5
db.pool.maxActive=20
db.pool.maxWait=10000